name    'jcalles-hqagent'
version '0.0.1'
source 'Custom'
author 'jcalles'
license 'Apache License, Version 2.0'
summary 'Puppet module for install hyperic agent 4.6.0 on RedHat an d centOS > 6.0'
description 'Puppet module for install hyperic agent 4.6.0'
project_page 'https://github.com/jcalles/puppet-hqagent'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
